### ISSUE TITLE
Is there a way to restore a dump using go?

### ISSUE THREAD

**Issue by Demitroi** [JamesStewy/go-mysqldump#12]
Hi, is there a way to restore a dump using go?

I tried execute the file but got the next error:

```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COL' at line 7
```

Also tried spliting the queries with ';' but doesn't work when there's a value with ';' inside.

Using the MySQL CLI or HeidiSQL works well.

I know that works using the cmd/exec package with MySQL CLI. But the target is use go only.

Maybe using a regex? any ideas?

**Comment by JamesStewy** [comment]
Hi @Demitroi.

According to this [StackOverflow thread](https://stackoverflow.com/questions/28548559/does-a-go-mysql-driver-exist-that-supports-multiple-statements-within-a-single-s) both [go-mysql-driver](https://github.com/go-sql-driver/mysql) and [mymysql](https://github.com/ziutek/mymysql) can be configured to run multiple statements in a single query. This may work.

Though I haven't stated this explicitly anywhere, the scope of this package only concerns the creation of mysql database dumps mainly for the purpose of simple, automated backups. If and how the dumps are restored, is out of scope.

Thanks, James.
